"""add trade guard mvp tables

Revision ID: 3578a817d51e
Revises: 6eb62ce3b43d
Create Date: 2026-05-28 12:14:25.949423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3578a817d51e'
down_revision: Union[str, None] = '6eb62ce3b43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('coupons_code_key'), 'coupons', type_='unique')
    op.drop_constraint(op.f('market_data_cache_cache_key_key'), 'market_data_cache', type_='unique')
    op.drop_constraint(op.f('payment_events_provider_event_id_key'), 'payment_events', type_='unique')
    op.drop_constraint(op.f('stocks_isin_key'), 'stocks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stocks_isin_key'), 'stocks', ['isin'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payment_events_provider_event_id_key'), 'payment_events', ['provider_event_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('market_data_cache_cache_key_key'), 'market_data_cache', ['cache_key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('coupons_code_key'), 'coupons', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
