"""Add completed_trades table

Revision ID: 4333c1cfe0d1
Revises: f273bc656ae9
Create Date: 2026-04-04 01:27:11.878041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4333c1cfe0d1'
down_revision: Union[str, None] = 'f273bc656ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('return_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('holding_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_trades_id'), 'completed_trades', ['id'], unique=False)
    op.create_index(op.f('ix_completed_trades_user_id'), 'completed_trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completed_trades_user_id'), table_name='completed_trades')
    op.drop_index(op.f('ix_completed_trades_id'), table_name='completed_trades')
    op.drop_table('completed_trades')
    # ### end Alembic commands ###
